package com.epam.training.jwd.online.shop.controller.command.constant;

public class RequestConstants {
    public static final String COMMAND = "command";
    public static final String SERVER_MESSAGE = "server_message";
    public static final String USER = "user";
    public static final String ADMIN = "admin";
    public static final String PASSWORD = "password";
    public static final String REPEAT_PASSWORD = "password_repeated";
    public static final String USERNAME = "username";
    public static final String FIRST_NAME = "first_name";
    public static final String LAST_NAME = "last_name";
    public static final String EMAIL = "email";
    public static final String PHONE_NUMBER = "phone_number";
    public static final String VIOLATION_MESSAGE = "violation_message";
    public static final String LOCALE = "locale";
    public static final String REDIRECT_COMMAND = "redirect_command";
    public static final String VERIFICATION_MESSAGE = "verification_message";
    public static final String CURRENT_PAGE = "current_page";
    public static final String VERIFICATION_CODE = "verification-code";
    public static final String MENU_ITEMS = "menu_items";
    public static final String IMG_FILE = "img";
    public static final String PAGE = "page";
    public static final String ID = "id";
    public static final String PRODUCT_TYPE = "product_type";
    public static final String PAGEABLE = "pageable";
    public static final String DESCRIPTION = "description";
    public static final String PRICE = "price";
    public static final String TYPE_ID = "type_id";
    public static final String PRODUCT_NAME = "product-name";
    public static final String CART = "cart";
    public static final String TOTAL_COST = "total_cost";
    public static final String COUNTRY = "country";
    public static final String TOWN = "town";
    public static final String TIME = "time";
    public static final String METHOD = "method";
    public static final String TIME_PATTERN = "yyyy-MM-dd'T'HH:mm";
    public static final String ORDERS = "orders";
    public static final String CODE = "code";
    public static final String CHECK = "check";
    public static final String TRUE = "true";
    public static final String SELECT = "select";
}
